"""
GitHub API integration for creating Pull Requests.
"""
import os
import logging
from typing import Optional
from github import Github, GithubException

logger = logging.getLogger(__name__)


class GitHubAPI:
    """Handles GitHub API operations."""

    def __init__(self, token: str, repo_owner: str, repo_name: str):
        """
        Initialize GitHub API client.

        Args:
            token: GitHub Personal Access Token
            repo_owner: Repository owner (username or org)
            repo_name: Repository name
        """
        self.github = Github(token)
        self.repo = self.github.get_repo(f"{repo_owner}/{repo_name}")
        self.repo_owner = repo_owner
        self.repo_name = repo_name
        
        logger.info(f"Initialized GitHub API for {repo_owner}/{repo_name}")

    def create_pull_request(
        self,
        title: str,
        body: str,
        head_branch: str,
        base_branch: str = "main",
    ) -> Optional[str]:
        """
        Create a pull request.

        Args:
            title: PR title
            body: PR description
            head_branch: Source branch (the new feature branch)
            base_branch: Target branch (usually main or master)

        Returns:
            PR URL if successful, None otherwise
        """
        try:
            pr = self.repo.create_pull(
                title=title,
                body=body,
                head=head_branch,
                base=base_branch,
            )
            
            logger.info(f"Created PR #{pr.number}: {pr.html_url}")
            return pr.html_url

        except GithubException as e:
            logger.error(f"GitHub API error: {e}", exc_info=True)
            return None
        except Exception as e:
            logger.error(f"Error creating PR: {e}", exc_info=True)
            return None

    def format_pr_body(
        self,
        dataset_name: str,
        location: str,
        labels: dict,
        service_account: str,
        request_id: str,
    ) -> str:
        """
        Format a detailed PR description.

        Args:
            dataset_name: Dataset name
            location: GCP region
            labels: Labels dict
            service_account: Service account email
            request_id: Request tracking ID

        Returns:
            Formatted markdown body
        """
        labels_formatted = "\n".join([f"  - `{k}`: `{v}`" for k, v in labels.items()])
        
        body = f"""## 🤖 Automated Dataset Creation

This PR was automatically generated by the AI Chatbot.

### Dataset Configuration

- **Dataset Name**: `{dataset_name}`
- **Location**: `{location}`
- **Service Account**: `{service_account}`

### Labels
{labels_formatted}

### Files Changed

- `datasets/{dataset_name}.tf` - BigQuery dataset Terraform configuration

### Review Checklist

- [ ] Dataset name follows naming conventions
- [ ] Location is correct for the use case
- [ ] Service account has appropriate permissions
- [ ] Labels are accurate and follow tagging standards
- [ ] No sensitive information in configuration

### Next Steps

1. Review the Terraform configuration
2. Approve and merge this PR
3. Apply the Terraform changes in your deployment pipeline

---

**Request ID**: `{request_id}`  
**Generated by**: AI Dataset Chatbot  
**Automation**: Vertex AI + Cloud Run
"""
        return body

    def get_default_branch(self) -> str:
        """Get the default branch name (main or master)."""
        return self.repo.default_branch
